
apiVersion: apps/v1
kind: Deployment  # <--- 升级了！以前是 Pod
metadata:
  name: demo-app
  namespace: default
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: web
        # 👇 记得这里要换成你的 Docker Hub 用户名
        image: flybirdhere/my-k8s-app:8
        imagePullPolicy: Always  # <--- 每次重启必须去云端拉新的，不许用本地缓存
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: demo-app
  ports:
  - port: 80
    targetPort: 80
